arch: ppc64le
sudo: required
services:
  - docker
install:
  - docker pull sangerpathogens/bio-tradis
script:
  - docker run --rm -it sangerpathogens/bio-tradis /bin/bash -c "git clone https://github.com/sanger-pathogens/Bio-Tradis.git && cd Bio-Tradis && dzil test"
